# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918695c25f3b49114aee232f3297230b0e26de2858a7be1404e7aa064f78c9e5209f9d38d36c33e36e7a9449d59a6cd25055f0e766c02b8c85629d1feb841d9f

test:
  secret_key_base: 44c525d83f9d085c01f3ab5957a68182526a246e5579fd1c584c1ab591052b35308b73960187eaac31ac51c3ac46bebaf9e21d3aa3520d3c6180c865d0e0fe21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
